-- =============================================
-- COMPLETE LOGIN FIX - FIXES EVERYTHING
-- =============================================
-- This script fixes ALL possible login issues
-- =============================================

DECLARE @AdminEmail NVARCHAR(255) = 'admin@khidmah.com';
DECLARE @AdminUserId UNIQUEIDENTIFIER = '20000000-0000-0000-0000-000000000001';
DECLARE @CompanyId UNIQUEIDENTIFIER = '00000000-0000-0000-0000-000000000001';

PRINT '========================================';
PRINT 'COMPLETE LOGIN FIX';
PRINT '========================================';
PRINT '';

-- =============================================
-- STEP 1: Fix User
-- =============================================
PRINT 'Step 1: Ensuring user is active...';
UPDATE Users
SET IsActive = 1,
    IsDeleted = 0,
    EmailConfirmed = 1,
    UpdatedAt = GETUTCDATE()
WHERE Email = @AdminEmail;
PRINT '   ✓ User fixed';

-- =============================================
-- STEP 2: Fix Company
-- =============================================
PRINT '';
PRINT 'Step 2: Ensuring company is active...';
UPDATE Companies
SET IsActive = 1,
    IsDeleted = 0,
    UpdatedAt = GETUTCDATE()
WHERE Id = @CompanyId;
PRINT '   ✓ Company fixed';

-- =============================================
-- STEP 3: Fix UserCompany (CRITICAL!)
-- =============================================
PRINT '';
PRINT 'Step 3: Fixing UserCompany relationship...';

-- Delete any existing (in case it's wrong)
DELETE FROM UserCompanies
WHERE UserId = @AdminUserId
  AND CompanyId = @CompanyId;

-- Create new with correct settings
INSERT INTO UserCompanies (Id, CompanyId, UserId, IsDefault, IsActive, CreatedAt, IsDeleted)
VALUES (
    NEWID(),
    @CompanyId,
    @AdminUserId,
    1,  -- IsDefault = TRUE (CRITICAL!)
    1,  -- IsActive = TRUE (CRITICAL!)
    GETUTCDATE(),
    0   -- IsDeleted = FALSE
);
PRINT '   ✓ UserCompany relationship created/fixed';
PRINT '   → IsDefault = 1';
PRINT '   → IsActive = 1';

-- =============================================
-- STEP 4: Password Hash
-- =============================================
PRINT '';
PRINT 'Step 4: Password Hash';
PRINT '   ⚠️  CRITICAL: The hash must be generated by your API';
PRINT '   → Run: cd Khidmah_Inventory.API && dotnet run';
PRINT '   → Look for the hash in console output';
PRINT '   → Copy the ENTIRE hash (starts with $2a$12$...)';
PRINT '   → It should be about 60 characters long';
PRINT '';
PRINT '   Current hash in database:';
SELECT 
    LEFT(PasswordHash, 60) AS HashPreview,
    LEN(PasswordHash) AS Length,
    CASE 
        WHEN PasswordHash LIKE '%Y5Y5Y5Y5Y5Y%' THEN '⚠️  SUSPICIOUS - Has repeating pattern'
        WHEN PasswordHash LIKE '$2a$12$%' THEN '✓ Format looks OK'
        ELSE '⚠️  Check format'
    END AS Status
FROM Users
WHERE Email = @AdminEmail;
PRINT '';
PRINT '   To update, run this SQL (replace YOUR_HASH):';
PRINT '   UPDATE Users SET PasswordHash = ''YOUR_HASH'', UpdatedAt = GETUTCDATE() WHERE Email = ''' + @AdminEmail + ''';';

-- =============================================
-- FINAL VERIFICATION
-- =============================================
PRINT '';
PRINT '========================================';
PRINT 'VERIFICATION';
PRINT '========================================';

-- All checks
SELECT 
    'User' AS CheckItem,
    CASE 
        WHEN u.IsActive = 1 AND u.IsDeleted = 0 THEN '✓ PASS'
        ELSE '❌ FAIL'
    END AS Status
FROM Users u
WHERE u.Email = @AdminEmail

UNION ALL

SELECT 
    'UserCompany' AS CheckItem,
    CASE 
        WHEN uc.IsDefault = 1 AND uc.IsActive = 1 THEN '✓ PASS'
        ELSE '❌ FAIL'
    END AS Status
FROM UserCompanies uc
WHERE uc.UserId = @AdminUserId
  AND uc.CompanyId = @CompanyId

UNION ALL

SELECT 
    'Company' AS CheckItem,
    CASE 
        WHEN c.IsActive = 1 AND c.IsDeleted = 0 THEN '✓ PASS'
        ELSE '❌ FAIL'
    END AS Status
FROM Companies c
WHERE c.Id = @CompanyId;

PRINT '';
PRINT '========================================';
PRINT 'SUMMARY';
PRINT '========================================';
PRINT '';
PRINT '✓ User status fixed';
PRINT '✓ Company status fixed';
PRINT '✓ UserCompany relationship fixed';
PRINT '';
PRINT '⚠️  ACTION REQUIRED:';
PRINT '   1. Get a FRESH password hash from your API';
PRINT '   2. Update the hash using the SQL shown above';
PRINT '   3. Try logging in again';
PRINT '';
PRINT 'If login still fails after updating hash:';
PRINT '   → Check API logs for errors';
PRINT '   → Verify the hash is exactly 60 characters';
PRINT '   → Make sure there are no extra spaces';
PRINT '========================================';












