-- =============================================
-- SIMPLE PASSWORD HASH UPDATE
-- =============================================
-- The hash in your database doesn't match "Admin@123"
-- You need a FRESH hash generated by your API
-- =============================================

PRINT '========================================';
PRINT 'PASSWORD HASH UPDATE';
PRINT '========================================';
PRINT '';
PRINT 'STEP 1: Get hash from API';
PRINT '   → Run: cd Khidmah_Inventory.API && dotnet run';
PRINT '   → Look for the hash in console output';
PRINT '   → Copy the ENTIRE hash (starts with $2a$12$...)';
PRINT '';
PRINT 'STEP 2: Replace YOUR_HASH_HERE below with the hash you copied';
PRINT '';
PRINT 'STEP 3: Run this script';
PRINT '';
PRINT '========================================';
PRINT '';

-- ⚠️ REPLACE YOUR_HASH_HERE with the hash from API console
DECLARE @NewHash NVARCHAR(255) = 'YOUR_HASH_HERE';

-- Validate hash format
IF @NewHash = 'YOUR_HASH_HERE'
BEGIN
    PRINT '❌ ERROR: You must replace YOUR_HASH_HERE with the actual hash!';
    PRINT '';
    PRINT 'Get the hash by:';
    PRINT '  1. Running: cd Khidmah_Inventory.API && dotnet run';
    PRINT '  2. Looking for the hash in console output';
    PRINT '  3. Copying the hash (starts with $2a$12$...)';
    RETURN;
END

IF NOT (@NewHash LIKE '$2a$12$%' OR @NewHash LIKE '$2a$11$%')
BEGIN
    PRINT '❌ ERROR: Hash format is invalid!';
    PRINT 'Hash should start with $2a$12$ or $2a$11$';
    PRINT 'Your hash: ' + LEFT(@NewHash, 20) + '...';
    RETURN;
END

IF LEN(@NewHash) < 55 OR LEN(@NewHash) > 65
BEGIN
    PRINT '⚠️  WARNING: Hash length is unusual';
    PRINT 'Expected: 60 characters';
    PRINT 'Your hash: ' + CAST(LEN(@NewHash) AS NVARCHAR(10)) + ' characters';
END

-- Update the hash
UPDATE Users
SET PasswordHash = @NewHash,
    UpdatedAt = GETUTCDATE()
WHERE Email = 'admin@khidmah.com'
  AND IsDeleted = 0;

IF @@ROWCOUNT > 0
BEGIN
    PRINT '';
    PRINT '✅ SUCCESS! Password hash updated.';
    PRINT '';
    PRINT 'Verification:';
    SELECT 
        Email,
        LEFT(PasswordHash, 30) + '...' AS HashPreview,
        LEN(PasswordHash) AS Length,
        '✓ Updated' AS Status
    FROM Users
    WHERE Email = 'admin@khidmah.com';
    
    PRINT '';
    PRINT '========================================';
    PRINT 'Try logging in now:';
    PRINT '  Email: admin@khidmah.com';
    PRINT '  Password: Admin@123';
    PRINT '========================================';
END
ELSE
BEGIN
    PRINT '❌ ERROR: User not found or already deleted';
END












