// Application Settings Models

export interface CompanySettings {
  name: string;
  legalName?: string;
  taxId?: string;
  registrationNumber?: string;
  email?: string;
  phoneNumber?: string;
  address?: string;
  city?: string;
  state?: string;
  country?: string;
  postalCode?: string;
  currency: string;
  timeZone: string;
  fiscalYearStart: string; // MM-DD format
  fiscalYearEnd: string; // MM-DD format
}

export interface UserSettings {
  firstName: string;
  lastName: string;
  email: string;
  phoneNumber?: string;
  language: string;
  dateFormat: string;
  timeFormat: '12h' | '24h';
  timeZone: string;
  notificationsEnabled: boolean;
  emailNotifications: boolean;
  pushNotifications: boolean;
}

export interface SystemSettings {
  // Numbering Sequences
  purchaseOrderPrefix: string;
  salesOrderPrefix: string;
  invoicePrefix: string;
  deliveryNotePrefix: string;
  grnPrefix: string;
  
  // Stock Settings
  defaultWarehouse?: string;
  allowNegativeStock: boolean;
  autoGenerateSKU: boolean;
  skuPrefix: string;
  trackBatchNumbers: boolean;
  trackExpiryDates: boolean;
  
  // Pricing
  defaultTaxRate: number;
  priceIncludesTax: boolean;
  
  // Inventory Valuation
  valuationMethod: 'FIFO' | 'LIFO' | 'WAVG' | 'Standard';
  
  // Alerts
  lowStockThreshold: number;
  expiryAlertDays: number;
  
  // Security
  sessionTimeout: number; // minutes
  requirePasswordChange: boolean;
  passwordMinLength: number;
  requireStrongPassword: boolean;
  
  // Email/SMTP
  smtpHost?: string;
  smtpPort?: number;
  smtpUsername?: string;
  smtpPassword?: string;
  smtpEnableSSL: boolean;
  fromEmail?: string;
  fromName?: string;
}

export interface NotificationSettings {
  lowStockAlert: boolean;
  expiryAlert: boolean;
  purchaseOrderStatus: boolean;
  salesOrderStatus: boolean;
  invoiceGenerated: boolean;
  paymentReceived: boolean;
  paymentDue: boolean;
  systemUpdates: boolean;
  emailDigest: 'daily' | 'weekly' | 'never';
}

export interface UISettings {
  sidebarCollapsed: boolean;
  sidebarPosition: 'left' | 'right';
  theme: 'light' | 'dark' | 'auto';
  compactMode: boolean;
  showTooltips: boolean;
  animationsEnabled: boolean;
  tablePageSize: number;
  showBreadcrumbs: boolean;
  showNotifications: boolean;
}

export interface ReportSettings {
  defaultFormat: 'pdf' | 'excel' | 'csv';
  includeLogo: boolean;
  includeFooter: boolean;
  footerText?: string;
  dateRange: 'today' | 'week' | 'month' | 'quarter' | 'year' | 'custom';
}

export interface AllSettings {
  company: CompanySettings;
  user: UserSettings;
  system: SystemSettings;
  notifications: NotificationSettings;
  ui: UISettings;
  reports: ReportSettings;
}

export const DEFAULT_COMPANY_SETTINGS: CompanySettings = {
  name: '',
  currency: 'USD',
  timeZone: 'UTC',
  fiscalYearStart: '01-01',
  fiscalYearEnd: '12-31'
};

export const DEFAULT_USER_SETTINGS: UserSettings = {
  firstName: '',
  lastName: '',
  email: '',
  language: 'en',
  dateFormat: 'MM/DD/YYYY',
  timeFormat: '12h',
  timeZone: 'UTC',
  notificationsEnabled: true,
  emailNotifications: true,
  pushNotifications: false
};

export const DEFAULT_SYSTEM_SETTINGS: SystemSettings = {
  purchaseOrderPrefix: 'PO',
  salesOrderPrefix: 'SO',
  invoicePrefix: 'INV',
  deliveryNotePrefix: 'DN',
  grnPrefix: 'GRN',
  allowNegativeStock: false,
  autoGenerateSKU: true,
  skuPrefix: 'SKU',
  trackBatchNumbers: false,
  trackExpiryDates: false,
  defaultTaxRate: 0,
  priceIncludesTax: false,
  valuationMethod: 'FIFO',
  lowStockThreshold: 10,
  expiryAlertDays: 30,
  sessionTimeout: 60,
  requirePasswordChange: false,
  passwordMinLength: 8,
  requireStrongPassword: true,
  smtpEnableSSL: true
};

export const DEFAULT_NOTIFICATION_SETTINGS: NotificationSettings = {
  lowStockAlert: true,
  expiryAlert: true,
  purchaseOrderStatus: true,
  salesOrderStatus: true,
  invoiceGenerated: true,
  paymentReceived: true,
  paymentDue: true,
  systemUpdates: false,
  emailDigest: 'daily'
};

export const DEFAULT_UI_SETTINGS: UISettings = {
  sidebarCollapsed: false,
  sidebarPosition: 'left',
  theme: 'light',
  compactMode: false,
  showTooltips: true,
  animationsEnabled: true,
  tablePageSize: 25,
  showBreadcrumbs: true,
  showNotifications: true
};

export const DEFAULT_REPORT_SETTINGS: ReportSettings = {
  defaultFormat: 'pdf',
  includeLogo: true,
  includeFooter: true,
  footerText: 'Generated by Khidmah Inventory',
  dateRange: 'month'
};

